name: Deploy existing ACR image to Azure Web App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy image from ACR
        run: |
          az webapp config container set \
            --name netflixx \
            --resource-group muzz \
            --docker-custom-image-name devopsacr123456.azurecr.io/netflix:latest \
            --docker-registry-server-url https://devopsacr123456.azurecr.io

      - name: Restart Web App
        run: |
          az webapp restart \
            --name netflixx \
            --resource-group muzz
